global using FluentValidation;
global using MediatR;
global using SecurityAuth.Api.Domain.Users;
global using SecurityAuth.Api.Features.Auth;
global using SecurityAuth.Api.Infrastructure.Identity;
global using SecurityAuth.Api.Infrastructure.Persistence;
global using SecurityAuth.Api.Infrastructure.Security;
global using SecurityPlatform.BuildingBlocks.Cqrs;
global using SecurityPlatform.BuildingBlocks.Validation;
